version: '{build}'

skip_tags: true

clone_depth: 10

environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version

build_script:
- npm run test

test: off
